config/routes.rb
Rails.application.routes.draw do
  get '/top' => 'homes#top'
  root to: 'homes#top'
  patch 'books/:id' => 'books#update', as: 'update_book'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
   @books = Book.all
   @book = Book.new
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :show
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed"
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="field">
 <span>Title</span>
 <%= f.text_field :title %>
</div>

<div class="field">
 <span>Body</span>
 <%=f.text_area :body %>
</div>

<div class="action">
 <span><%= f.submit 'Update Book' %></span>
</div>

<%=link_to "show", book_path(@book.id) %> |
<%=link_to "back", "/books" %>

<% end %>

app/views/books/index.html.erb
<div>
  <%= flash[:notice] %>
</div>


<h1>Books</h1>

<table>
	<thead>
		<tr>
			<th class=nav-list>Title</th>
			<th class=nav-list>Body</th>
		</tr>
	</thead>
	<body>
		<% @books.each do |book| %>
		<tr>
			<td><%= book.title %></td>
			<td><%= book.body %></td>
			<td><%=link_to "show", book_path(book.id) %></td>
			<td><%=link_to "edit", edit_book_path(book.id) %></td>
			<td><%=link_to "Destroy", book_path(book.id),method: :delete, "data-confirm" => "Are yuo sure?" %></td>
		</tr>
		<% end %>
	</body>
</table>





<h2>New book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/books', method: :post do |f| %>
<div class="field">
	<span>Title</span>
	<%= f.text_field :title %>
</div>

<div class="field">
	<span>Body</span>
	<%= f.text_area :body %>
</div>


<div class="action">
	<span><%= f.submit 'Create Book' %></span>
</div>


<% end %>

app/views/books/show.html.erb
<body>
  <div>
    <%= flash[:notice] %>
  </div>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <p><strong>Title:</strong> <%= @book.title %></p>


  <p><strong>Body:</strong> <%= @book.body %></p>


  <%=link_to "Edit", edit_book_path(@book.id) %> |
  <%=link_to "Back", "/books" %>
</body>

app/views/homes/top.html.erb
  <head>
    <%= stylesheet_link_tag "homes", :media => "all" %>
  </head>

  <body>
    <h1>ようこそ <strong>Bookers</strong> へ！</h1>

    <p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>

    <p>印象を共有し交換することができます</p>
    <p><%= link_to "start", "/books" %></p>



  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>